-- MySQL Script generated by MySQL Workbench
-- Thu Jan  6 14:24:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema artists_paintings
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artists_paintings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artists_paintings` DEFAULT CHARACTER SET utf8 ;
USE `artists_paintings` ;

-- -----------------------------------------------------
-- Table `artists_paintings`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artists_paintings`.`artists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artists_paintings`.`paintings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artists_paintings`.`paintings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `price` DECIMAL(19,2) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `artist_id`),
  INDEX `fk_paintings_artists_idx` (`artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_paintings_artists`
    FOREIGN KEY (`artist_id`)
    REFERENCES `artists_paintings`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
